import type { Metadata } from 'next'
import { Nunito } from 'next/font/google'
import '@/style/globals.css'

const nunito = Nunito({
  variable: '--font-nunito',
  subsets: ['latin'],
  weight: ['400', '600', '700'],
})

export const metadata: Metadata = {
  title: 'Payline Web Portal',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={`${nunito.variable}  antialiased`}>{children}</body>
    </html>
  )
}
